name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v23
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Run linters
        run: nix develop --command make lint
